force-app/main/default/objects/Case/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for response</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseHelper.cls
public inherited sharing class CaseHelper {

    @AuraEnabled(cacheable=true)
    public static List<Case> getFieldManagerCaseList() {
        return [SELECT Id, CaseNumber, Assignee__c, Assignment_Status__c FROM Case];
    }

    @AuraEnabled(cacheable=true)
    public static List<Case> getServicePersonCaseList() {
        //return [SELECT Id, CaseNumber, Assignment_Status__c FROM Case WHERE Assignee__c =: UserInfo.getUserId() ];
        return [SELECT Id, CaseNumber, Assignment_Status__c FROM Case ];
    }

    @AuraEnabled
    public static void rejectCase(String caseId) {
        Case assignedCase = [SELECT Assignment_Status__c FROM Case WHERE Id =: caseId];
        assignedCase.Assignment_Status__c = 'Rejected';

        update assignedCase;
    }

    @AuraEnabled
    public static void acceptCase(String caseId) {
        Case assignedCase = [SELECT Assignment_Status__c FROM Case WHERE Id =: caseId];
        assignedCase.Assignment_Status__c = 'Accepted';

        update assignedCase;
    }
}