force-app/main/default/objects/Case/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for response</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Is_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserHelper.cls
public inherited sharing class UserHelper {
    @AuraEnabled(cacheable=true)
    public static List<User> getUserList() {
        return [SELECT FirstName, LastName, Username, UserType FROM User WHERE Is_Assigned__c = False];
    }

    @AuraEnabled
    public static void assignUser(String userId, String caseId) {
        User user = [SELECT Is_Assigned__c FROM User WHERE Id =: userId];
        user.Is_Assigned__c = True;
        update user;

        Case assignedCase = [SELECT Assignee__c FROM Case WHERE Id =: caseId];
        assignedCase.Assignee__c = user.Id;
        assignedCase.Assignment_Status__c = 'Waiting for response';
        update assignedCase;
    }
}